version: '3.9'

services:
  tgbotdemo:
    image: ghcr.io/postoev-alexander/tgbotdemo:main  
    ports:
      - "5000:5000"
      - "5001:5001"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
      mode: replicated
      replicas: 1
    environment:
      - ASPNETCORE_ENVIRONMENT=Production