version: '3.8'

services:
  tgbotdemo:
    image: ghcr.io/Postoev-Alexander/TgBotDemo:main  
    build: .
    ports:
      - "5000:5000"
      - "5001:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production