version: '3.8'

services:
  tgbotdemo:
    image: ghcr.io/postoev-alexander/tgbotdemo:main  
    ports:
      - "5000:5000"
      - "5001:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production