version: '3.8'

services:
  tgbotdemo:
    image: ghcr.io/postoev-alexander/tgbotdemo:main
    container_name: tgbotdemo
    ports:
      - "5000:5000"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
      mode: replicated
      replicas: 1
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    networks:
      - nginx_net

networks:
  nginx_net:
    name: nginx_net
    driver: overlay
    attachable: true
    external: true