name: GitHub Actions Demo Copy file to server
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest  
    permissions:
      contents: read
      packages: write
    
    steps:   
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      
      - name: Copy files to target server via scp
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          port: 22
          Key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "./README01"
          target: "~/.deploy/${{ github.event.repository.name }}/"